const subjectTypes = {
	FETCH_SUBJECT: 'FETCH_SUBJECT',
	SET_SUBJECT: 'SET_SUBJECT',
	ADD_SUBJECT: 'ADD_SUBJECT',
	UPDATE_SUBJECT: 'UPDATE_SUBJECT',
	DELETE_SUBJECT: 'DELETE_SUBJECT',
}

export default subjectTypes
